{
  "active": false,
  "connections": {
    "Telegram Trigger": {
      "main": [
        [
          {
            "node": "Telegram",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "createdAt": "2025-04-09T16:01:29.128Z",
  "id": "o60hcWoZs4wgfras",
  "meta": {
    "templateCredsSetupCompleted": true
  },
  "name": "[UDIA] Bot telegram errores",
  "nodes": [
    {
      "parameters": {
        "updates": [
          "message"
        ],
        "additionalFields": {}
      },
      "type": "n8n-nodes-base.telegramTrigger",
      "typeVersion": 1.1,
      "position": [
        0,
        0
      ],
      "id": "cc607a26-3ed7-4441-971e-8ba1020be3a0",
      "name": "Telegram Trigger",
      "webhookId": "ce337140-923f-4ca8-a0b9-168c4bce3402",
      "credentials": {
        "telegramApi": {
          "id": "3LRM6Aj1ndJe6IOw",
          "name": "Telegram account"
        }
      }
    },
    {
      "parameters": {
        "chatId": "={{ $json.message.chat.id }}",
        "text": "=Eco:{{ $json.message.text }}",
        "additionalFields": {
          "appendAttribution": false
        }
      },
      "type": "n8n-nodes-base.telegram",
      "typeVersion": 1.2,
      "position": [
        220,
        0
      ],
      "id": "9ba0c75e-c9cb-47f4-8f88-66a919d9917c",
      "name": "Telegram",
      "webhookId": "e8da441e-4752-4c85-b40b-f0d9acb2ae58",
      "credentials": {
        "telegramApi": {
          "id": "3LRM6Aj1ndJe6IOw",
          "name": "Telegram account"
        }
      }
    }
  ],
  "pinData": {},
  "settings": {
    "executionOrder": "v1"
  },
  "staticData": null,
  "tags": [],
  "triggerCount": 0,
  "updatedAt": "2025-04-09T16:21:30.000Z",
  "versionId": "7d2aaf46-116b-4b55-841a-5ec49772348e"
}